---

- name: Ensure system packages for docker are installed
  ansible.builtin.apt:
    force_apt_get: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
      - python3-setuptools
      - python3-pip
    state: present
    update_cache: true


- name: Ensure Docker GPG apt Key is added
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: Ensure docker repository is added
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present


- name: Ensure docker-ce is installed
  ansible.builtin.apt:
    name:
      - docker-ce
    state: present
    update_cache: true


- name: Ensure Docker module for python is installed
  ansible.builtin.pip:
    name: docker
