---

- name: Ensure systemd cached resolved is disabled
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNSStubListener=yes'
    line: 'DNSStubListener=no'
  notify: restart systemd-resolved

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
