---


- name: Install qemu guest package
  ansible.builtin.apt:
    force_apt_get: true
    pkg: qemu-guest-agent
    state: present
    update_cache: true
  notify: Restart qemu agent


- name: Start qemu agent service
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true


- name: Flush handlers
  ansible.builtin.meta: flush_handlers
