---

- name: Include distribution specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['distribution'] | lower }}.yaml"

- name: Ensure ssh connection is hardened
  blockinfile:
    path: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -T -f %s
    block: |
      PermitRootLogin no
      MaxAuthTries 3
      MaxSessions 5
      PasswordAuthentication no
  notify: Restart sshd

- name: Flush handlers
  meta: flush_handlers
