---

- name: Ensure server is configured
  hosts: pihole.lab
  become: true
  roles:
    - role: core
      timezone: "{{ i_timezone }}"
      ansible_public_key_path: "{{ i_ansible_public_key_path }}"
      locale_list: "{{ i_locale_list }}"

    - role: update
    - role: sshd
    - role: vm_guest
    - role: firewall
    - role: docker
    - role: pihole
      admin_password: "{{ password }}"
      docker_image: "{{ image }}"
      timezone: "{{ i_timezone }}"
