---

# do not run ssh hardening
- name: Ensure server is configured
  hosts: proxmox_servers
  become: true
  roles:
    - role: core
      timezone: "{{ i_timezone }}"
      ansible_public_key_path: "{{ i_ansible_public_key_path }}"
      locale_list: "{{ i_locale_list }}"

    - role: update
    - role: proxmox
      ssl_key: "{{ i_ssl_key }}"
      ssl_cert: "{{ i_ssl_cert }}"
      default_gateway: "{{ i_default_gateway }}"
      network_mask: "{{ i_network_mask }}"
