---

- name: Setup system from dropbox sync
  hosts: workstations
  become: true
  tasks:

    - name: Create workspace directory
      become: true
      become_user: luka
      ansible.builtin.file:
        path: ~/Workspace
        owner: luka
        group: luka
        state: directory
        mode: '0755'

    - name: Link directory
      become: true
      become_user: luka
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: luka
        group: luka
        mode: '0755'
        state: link
      loop:
        - { src: "~/Dropbox/WorkSynced", dest: "~/Workspace/Sync" }
        - { src: "~/Dropbox/Archive", dest: "~/Archive" }
        - { src: "~/Dropbox/General_reference", dest: "~/General_reference" }
        - { src: "~/Dropbox/Project_reference", dest: "~/Project_reference" }
