---

- name: Ensure workstation is configured
  hosts: workstations
  become: true
  roles:
    - role: core
    - role: update
    - role: sshd
    - role: firewall
    - role: docker
    - role: workstation
      root_password: "{{ root_pass }}"
      users: "{{ users_config }}"
