---

- name: Ensure workstation is configured
  hosts: workstations
  become: true
  roles:
    - role: core
      timezone: "{{ i_timezone }}"
      ansible_public_key_path: "{{ i_ansible_public_key_path }}"
      locale_list: "{{ i_locale_list }}"

    - role: update
    - role: sshd
    - role: firewall
    - role: docker
    - role: workstation
      root_password: "{{ i_root_pass }}"
      users: "{{ i_user_configs }}"
      install_nvidia_driver: "{{ i_install_nvidia_driver }}"
      root_ca_cert: "{{ i_root_ca_cert }}"
