---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: media-cert
    namespace: media
spec:
    secretName: media-tls-secret
    issuerRef:
        name: nginx-clusterissuer
        kind: ClusterIssuer
    dnsNames:
        - media.cluster.lab

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "media"
  name: "media-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - media.cluster.lab
      secretName: media-tls-secret
  rules:
  - host: "media.cluster.lab"
    http:
      paths:
        - path: "/transmission"
          pathType: Prefix
          backend:
            service:
              name: "transmission"
              port:
                number: 80
        - path: "/sonarr"
          pathType: Prefix
          backend:
            service:
              name: "sonarr"
              port:
                number: 80
        - path: "/prowlarr"
          pathType: Prefix
          backend:
            service:
              name: "prowlarr"
              port:
                number: 80
        - path: "/radarr"
          pathType: Prefix
          backend:
            service:
              name: "radarr"
              port:
                number: 80
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: "plex"
              port:
                number: 32400
