---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secret
  namespace: media
spec:
  encryptedData:
    password: AgBSpQT9G90XzkVZJ8I+jkDgBDAffax32iaIcrz1IWKj9bV1HMiH36508UGFSoYjX/BF/1aA2MkZr36t70M469LngjMlpnJyhEQTWdwr1WRdNWDXtvGApAtbzHt912Y6RXYd2DX3yzQhpM4tQwaoO3hgXKECsZuHrRhC0OugoPtaiKJPZknNqL4QEW2LoXVIGuaW22+DJptQWRX1Eb90UHKbEp4Efv4fq+T1vEblo0xL9b5lmP7Wo9YCZdTNMPfRU7Z6aOLn7LWGWixSaIjBPahmNRgJr+UJK7VmVYoWZJPiGvjaTunwPPW+g9FV/y7Mr/DkbB6gJZgmx7UrvKSGG5T5pElwRFQ32w+BmXmzPg5sGB/LGO1D2IB5UdseW278WgOVmCZIdFW67c4ap3sFn3hwv/gmKPj/MBd7Vpr2ZxWU0Xu2d4/Y4jN3qOPKB96oJ7tlIMHtQnRhKWWEsAVLFOcWr6trlfB0OEJhDQtpOoERV9pUsSxjXSnEtURGBFpwhFnT7yeN9R2EmxeD2mcT9Wo6B2vSOiZ38JS/gxkK9p4sxIxPCH+D74pbY/gFT1lPjxsTbG7knqT+MDYEGiGzM0zmrSTht8ZrfWtRCQ+qq5Ln1zfSy9S046Ok5d8aWkI5/6phXjgJATWp88mobP2r0zg0o1kaMhia/3GBqpoBi/dhY3d8MrutXpJr18mM2nNVUMVC6nHlfTJvmHDvy/SS8TZEBYtaaA==
    username: AgBnGqIicqFrGJvMp/nVQNL56z0qy89Q4dujAg652byZGNPZvXk7wY7xPQk/q9aAsOfVZv5L0RZyWkmLWxx0arX0ks4DSQCXoOOTjtDTn1gmz7DU0WYNXd/VvKCKKdHrQuR4xxeKgfS2QTUp/ohBk6HNQX3MQDWA0Av/BVoZKhTLKUjVukFI7WXH6pJ0W71aaHPHPgCz5kFyUAZxgdnXoiFsejtDj0n3t2w6/n2/jLxf9Wf9MzhMnylAqykHiaaPQe/Ym0cueXvn7Yh362vlPdjqsTTxOyJdVKvIrD/Pr1KpZ1K7fbdxcsu7j+Lh0zq+2RwFwcbR6SF3Eb5bhVcc+46lBKMh7j55zI+1927l+HTqaWtt48TwM2q/z3ZVU+c7EB4ua28bcmJD67ZAYmflroJsPxQmQxAFpEToarHkXX2EYyHwl/IjAoPYgD3OroiqxdCf4nfOHsogpHDgjjUfUsRmnAifvrPbdPwE/jwOdSXwj+TLiW+DFWZOI8HiJMpmVByA495YeSiayKMQpG8T87wXQZyhU2vcHz8SVfZnJMcF5XCJ9R8JFLUh59dWjRG3YQsi+rXgafskUBV/vpRnNq/8GBrHTo4U49eA8OA4MgnMeteXtarNL6p0g8xuVvexaPKuDpSQID38Bzi9ySUpdUhvdvsol/Ko3Ji3AS5KH7lJtuZHfXb5wCbBXk424pc74QbACMNv9RcdbNxQ2+lgD7p92eWX9F8=
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secret
      namespace: media
