---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secret
  namespace: media
spec:
  encryptedData:
    claim: AgBcK3flgpnlY3w0UX5VpErH/r5q+i5DLw1q/RmhjsR/5ZvhH+h4XFSCo8ta7EzqKXClSbcRhRMU9sPCmLotSc04dwDtJvvWRSe5kuzGghyiH0cJGJk5Zzl2qR00LTcMBeeg5G/lvBOcbsdKpd90qvIhU+4Xb9EJrpMHbxEsB1fdp5suifJg6zWU6ZUtYgWCoJOIvtlQer1/TAcdzSUDYO179ddKdMwv0Hp6MnZCasJICCMQ1IWwHVDeiFKNwAQcUgOcbwY2jYVSlPeUbER+uD9pAw1NIr+NZFiikrkufNCQgD6ZgEM9vTYN5B25jmZsGJ7G22sSq422wqq+lY0YjjQLByoIFdLyNVlrN2/pyZTOmafZcxBtznaEtg/J2rst+KiKafR4AGagXEJiIEUNQFuJGY+R62IdJknYmgbYZpgJhdLXuH7+64v19ndEKS9imE+gW1luTmgB0Dw+wnBcJY7uKiVunibjGguvAb+c7S/hmcp9Cihhfj+vsrlBYyvd8kNgdTS7XlVAHtpm+3AbnPPYTnrLSvg8+wAE3SkM23SKnGXr/uShXiF8nYB9r0s6BVtMe/OHe/EZZftQimNWMbmUYUlUExD665sW1hnxEiLsU6sQvdggCHangf97YmI+IUwPeF9soDPLE9wHIy5AP6MzNISRYWptqCREmlLH8NAzkENs16jKJPoWE8YKjv146jO1n1WwfsaUBZGZxQOanFIVTkHfd/MLa9yHWA==
  template:
    metadata:
      creationTimestamp: null
      name: plex-secret
      namespace: media
