---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secret
  namespace: media
spec:
  encryptedData:
    claim: AgCqMiw4RVc1GsHeg9Rta69LAjQ7/HmZyPD4kLmgHh9fLJe1dqa5QDh23ANTmEKOq7YhIdK3umK9yjSkmn7mwHkgYUZ05Op+EoyJmcdzMZnKldU8EpsU3fADWaXrfkR7fbxsjX8pKw+ggr42A/tqmnMBzDjp1NGyI97vb/W7BmvOUPTHxmqVUWx0jnDJRlGD0/DLewYytVpGbICDWPVxjZve1ouCMdV/fBTGm2t1e/9wedzxS2aC/2x65Vw+cajgnI6gl9i0dd1UVUBcPuEFgUXnytelZ7X2Tf0mJ93Rq9rtIl9rUPR3ZVh1+8psl37P6uH0gAdeJ2hos852JJu9x4N9jy3WRUbfr6RqG+6Ta7+10P0RN6kHTHiu0NQEMIbe/ppXpxB+YryvubUMp9WbpO+huNVz+0MI+lEHjC/e2QH/3TYhfnv6RSBF3Q+GNsdhF30Moofx2OG3q+3S0iNxxONDh/jFiTaV1nnnhpfxEmLT9htp5TI5rLtBoTXfxtYw2h67q9nQ4FhxKNwzIv5ewJXSAa5SDzVmfmF51YXNFf3FuaRJUEj9uY9EWrXuecV06Mx4U8Ej3H/GlHSzSzAInsX2+RwSMpUPl2vjOnPelyGOmCXAyYvUYnHktv6LF+RRA5o/8Kti85F9fJwPC7gUZJqcWgXooeU6KPP6CHDXxzf1SRsU8qppkCPOuzIvllhUaBamxBOPJLjCuJ1lo+zi7Fx6dMbcmmrEZSRlsg==
  template:
    metadata:
      creationTimestamp: null
      name: plex-secret
      namespace: media
