---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secret
  namespace: media
spec:
  encryptedData:
    claim: AgBJQ0R6pcK303G0lLzRgR0fuH7E/GAupn6lwGre4UlYsKmqNXEVF+F834Q+dCQt2AALJAkxeFhGotdj/HCojuiwLYRNTkSMv3SMiZBSj0V8/bSn4iszuKa60eRs2NM5VqB6PPS15dEnotRERKVEK+Jx2J/ZHcNBVwmRoR3hj5swr7x7rJHXYi9IPXdXJmqlb9t0W4TxeOPnKg6wTQLFdOzyBHfKu7OhNrEajWBRUI2JlcqHGmknGKg+r9y7nPbqntjr7X8N+4g2bYCSgNfNJISo/QiMBP2oBLlLqW/av63lgpH2fdkd8hjDfxiuo5nDTyZ2iNxkv29zTmxwZxzeYhS/8//VN/xvaBSKMskMFqO3VO6B46q4gNtNpiRRvK6ObHcTIQEvfHkm11uQT80cXFRJsTJWbU7MDHymS389ISLr/hhYmwGAKOJf4871RuTSbiRiXuLQaBcaTsiR/2D9pNKZKqYfEVLFuY84yC4bNXXOEfWX51B7aotE9FFo3doqobkDASMDhcfDqJ6MV2dl9XjpDS+lhCW3GuAaWfUB6Huu8U+UQ2CssUg0tJ/uBUrwGoosFI+KtF+C8De83yihnHFOgCP54UHEPSnoUzMa90YAe4akiECcFcqhimDVbhoi8FHgrGnf4eeUQeetxusi/Goyu37slOEuVQdol7lIGet9Y4c/Hjkbu8EwYbNIXaX39t/5q6BQq1c7x4o4LTTxN87mXZNr9uV8C2yldw==
  template:
    metadata:
      creationTimestamp: null
      name: plex-secret
      namespace: media
