---


- name: Change root password
  ansible.builtin.user:
    name: root
    password: "{{ root_password | password_hash }}"
    state: present
    update_password: on_create

- name: Include instalation of base packages
  ansible.builtin.include_tasks: base_packages.yaml

- name: Install paru package
  kewlfft.aur.aur:
    use: auto
    state: present
    name:
      - paru
  become: true
  become_user: ansible

- name: Include nvidia drivers
  ansible.builtin.include_tasks: nvidia_driver.yaml
  when: install_nvidia_driver

- name: Install cups
  ansible.builtin.include_tasks: cups.yaml

- name: Include window manager tasks
  ansible.builtin.include_tasks: window_manager.yaml

- name: Include transmission
  ansible.builtin.include_tasks: transmission.yaml

- name: Include installation of root certificate
  ansible.builtin.include_tasks: root_certificate.yaml

- name: Include packer
  ansible.builtin.include_tasks: packer.yaml

- name: Include ansible
  ansible.builtin.include_tasks: ansible.yaml

- name: Include kubernetes
  ansible.builtin.include_tasks: kubernetes.yaml

- name: Configure users
  ansible.builtin.include_tasks: users.yaml
  loop: "{{ users }}"
  loop_control:
    loop_var: user
