---

- name: Install transmission
  community.general.pacman:
    state: present
    name:
      - packer

- name: Allow packer custom binded connection
  community.general.ufw:
    insert: 1
    rule: allow
    port: 8802
    comment: "Allow packer port"
  notify: Reload ufw

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
