---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgA1HftX7fE+uP6cNvljWY8S17zDqBJnJ2xNUAd8ahkxhCP/k+sI8acoS9J/sS1ulCLg3Hfw+v8EQTuPIKF8rGlHveIqFdITDkrDjP7kDnV/S0PWMDAVIbQN7vp0adLD0gmShK9rtoMZmGyfN7jEoLHPbYlA3Qb71DEQAbEJYEeFZ1L26GAhorawsob/sztecpE1yVbQHTji39er+LG241TbWSuy8h5QuAD4w9QPB9GaLj4b0dZZLMVp3nRv+hZRc9bpqw0gz4xPV0AtLJDvDiVbeX5fMOyaUtLc4eNFtWY8ZI4m0sLWTyz371pJ8blsx9MzPoflTjf3JDYQFftmieWbL9Ko5m7rNavi0C6KZ7V5UYMAu0qrZk2pMiqK/G3y/OnWbv62Mn/qqromnShbKAhBjZgHCry0QakS1Ds6kAczccreQvVGI1FklWS1dmtycjWmQVl9ZdiImHQLcyXvwjrfTqCVIi6Ocf34rBDdEW0RNGeLQgKkZPq8O+Su7NMMhvKCsSyUVGeHW59AnPcc4zEcG7fu/qPSeOL2Xot7lpPHRkchkfjxW9A/VzRpAmeO3nEKYjMgqckt4tp3hBHHAK5nIp5a8iHRbi/d3NHsUnaXZmMKi6WX5/mauXRNJU4RlDFYnOKLkymLbYGqidUw5EDbb/Hc+oFCRTQ1OymEPnxXbF4ESxYXB1l+KMPzkv+QVaHEzc9HxR7YVjVcOFJLIO7M1p9FESRYUC3K/TpDF88UPTV2M5ETLscKwOOH0l78P20hiIhRR8yQeHlW+GNqq+3+4XzvO3INAyqxL8TAiMJd3hDnbROGWJMC/T/+mXFZ3VcYfFHFZzdRBcAIT7U564pe0f/z8TAjbKzY/+59u7NNbA03/+aBQJVdtRgSLGY7oppUHOZYEfBmLMj9rrsISfBZ1H6lePd56dx2bBmBolpFImUMou6TbM8E6f2Cs07GIbQhuSDpK95JN9ohVvaWOmN+wU0bv/5A9kPcSLcM9slSD2uUHfpivgOXeHgcc1sW/k1ZhwuWIyYOOSMj1SjIuUbcmC8dLjM5rRcWjr51RQEdALp+2XfplowMCyprBtNLRo6FXgQTp0Kidt2w0c3A2D6oIpyjMSTPuGJqz2DaRSYzqIQ1tCzE0dAxGg+IVzNgCK7++fhoRehBHgyM8sMUXA2RF5NDxdSo5NQck/FL0sZbCkk7BoJiFSNcbyoMKDiG8WmD4gxYdCtm7u5uSo02z+IVsZ22W8in0zCTXvp1lj398qZUqKNJ+Kjj9Pe/PFtS6au95ZYeEBcDf4ZCaT5NdHU=
  template:
    metadata:
      creationTimestamp: null
      name: client-info-secret
      namespace: synology-csi
