---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgAzniYXHHarYZO3zHCK0AGQl/1yi+vHzGIDavk3d8To631VcJjpWQWUjhsdIGqYjdEyXg5ejLkPNdI+1Pg9am0eGf9U08dI6D441RnmZzWt7U5RrFNCkmt36IX0sj0lkdTCWMKuf6HHeNvTsXHdz2HKxZ60VVYSDwbJOEGbsn7E85NKWfrhAorH77Lxyg0+ffWS3Kyzqal7kYq+hb/IaOk2bx9e5D816poQsHyMIO/YJdeyOiBEbvORj6O8f1sEUwuN7Esd3FmmuCOqe0jtFcN4sPf19/puu82172G4Vl+tX2xgw6kEJ8hISBBHIsN9Qw1LIhuxV42ljfCWLL37GfJSQU/o2ppdK3YouGO2/TwVNOmNXbgj4nwzXjwE9yYg7dpYf0UWE7uP3TmH5Z9x8vuFAAdSB2v7zlG6WttWZIAcFlRD5b2MCTet3FDK8V5InzLU/NXS5gOhWFhQIX47HoTtBlok/T+v+vvkeQFVAia/ineNkl62pwpAj53scDmATXNu3+nXx0OSazULZVazqDb4VHhLya23V3IsPwlSvGmYz7w5sxji5hqNHYmnhO6HON5zktd4q/iUe6HBiuVhaamoR62EAx7saWgkY7PLoy7yzwxVZijN7uLATQIDxDwIb+Jkffup9MHfLshJfui+xhEIrYG+0ogqDUHl+4fpLLCKAVfn7uD1ZNovDw+yDQdGr7SIBo88YQFl3hzX7+3bZMNilbZBCAzMISQXjtp4OngUW3Hb4QzXUQpxZDfJmCw9pBGk1HZSQyqHw2bqoHsaT+fi8x5eV0YJwbon9IrGzKCnHJg5AVRCnsVOZJAw++eFabnb58uLG3zg9n2vAoh/R/2OPMJTuwFbx4bcMNy5YRESi/k3cImRbt9ib/Kz0rsZby3stWzWdnGRNcwK06kDIDM+Xsp8SXHZSh+DZp7bAuDWGO5OvbXIaLbgIMsYZ6kPswEr2kFjKZbd9aXF8z5vls7lfkibTr5S+folrzhqaWj35mOrsycx1ylstoPQxPiEnAvTTg5V8whYnBKbHPeB35J34/yYO54mx0vAAIucFKILeV4f8SMQHp6A0RXo3fB0JWU5/Ldw3/8mPs91d1n+zL311QPZUs9Y3iJFcj48RminjN2TRjT9twYpZbNtMGJKrxIOMe8e0m3Cq3NnSnh5XCeBsOjluWeD72nMiVc7sewF93EMY4BdzwL6t96pxJDJiOyKGfDI9gCAfsvGaQUWws+PRzvTLAGo+PPW6UPJ3QLe18v2QSJ+nVqe6zbOO+dkWMNsBIfK2aL1JhxtwKFgiTMS
  template:
    metadata:
      creationTimestamp: null
      name: client-info-secret
      namespace: synology-csi
