---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgBLk0tgt6O1YsJlqvViOBmyY+FaijWbsBsyhb0aoPX6IoTzsMNYxTq8WfQVKGMC4BvYgUQHE9i2FOC5Hj3woDExKWv5RtwokcD1qUpR9qf9lLHTZGZajZfdD1Degy1I3fxyp+CQL9gwel9LAn4F1kWd4T+VPJfX7Ofz5PDree6fp+xzOjr8zVBCQqyYMgUlPQyNJ8wpNEpC8KDgRWP+qcr9dKFiwVGKmMNwYcCFlTMW253ysxPKsjJtsxdHn9pUHfbN9L5IK1H6sXTvqJlN2K8MOy8aBPbM0IWcpR7KUUrWDY+SHgN4/hyn6xTmLYWK0pSwaumbb1NOy7eTQbY/fCTOwm0Im3olYnvGGNZ3Q6cWtRygC228HyuGMCwL+vx5tXjFXsUvUNACiZQeFgxLfNc1+S0OfSHryhXywABTlwxyE5SOMej2audyXknPAZAPJF/GnIVI4rj6VRxg4SG/q+w8DTic+slseT2owU/0p2lsRSsNgv0DBAE0O4wJTs1UTeULZbFTWba4XrD3hQPVNxBZWmGOVizSjOiunZliUommWIIcNKVHQOR8Q+lpexIq8+qgE80idv6P/H17o3ZCRrWwvVBDsB9x5L9eiHhCeBowqoISxfjOl0gMEtP6VmqtblEf+TY/YOolR74lRDlhCxtFD5n9/bmzqgqBLdKli5KpLFIiIJqoVU3nSl97uZO+dMZz85ukf1WNHNgjxN+k4kWuIrlLk3CW7Xz1zzUvZzohFS4A+y8CIoIOQe4Gh9EGRm2i5jcQAVpbdxyJFyOvdUgNO1eFqE8dzZGFvOhB/KA/S/rUkPV3+eDk0jQlQUlQP+MkEeO0bAkUg6JEocPdxCWFSR7iCmhdvrc+BHESB0ONv0UjZ6UmxKSeVfISdmY6uAkjs1GKN/4OctctGzTHCv4z/yXfR2+f8iIiNLr33DT9Co9I9I+pA7SnT1w5tUWstdpQFB27/xrh+pLF0kqdX8Kg86DHLrF8NlhQjKkJSx4cRKiMy6wUmpQhurCxnyFZ/UVuaYODnQFSQLDSG8aXcaw2V0qjhqfD0lCngcCHJ9rOeUPk9moUb2zBYfAm0dhTahm1zOeWDQsAqVp7fX1bAoPzIqWOBO6hzHZ2RjXF9uKjfEAN3fS/5lmfQdkGmhW4qYT58JAkHRfN9XDW977NsdX3X6oYMay15EVwiHkHxb5jKz2u3NGx9I4tM9+LUYRGAXV2pFnhzf/lfHkbL/b6++cT5j0Fhsp7sQMO+ae7Um8VM04OBfB3WtlFNUaMvQBGM9Xb2Og5/ly2H9hiIDhS2VE=
  template:
    metadata:
      creationTimestamp: null
      name: client-info-secret
      namespace: synology-csi
