---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgCVjqGCVQQJvYAVwXdzmwqeihTVGhg95ce2TkHc5JjQY+ozfr1e8zrIm052ttJxwt3YwLUyIfCsT6LTvxUSZnzyRdmw+KvYMNbU84GlF5KlrwhI6qmQoNTz/20WvbaclU8tvYwJN6bAJxGvhcDUfjrusYfxNNhZ//O/ltc7W6RgfQXMr1BwqpkTCEfH3YNPo0TqthQsPjcGTCw1Tq+t5BgTLLuE2ffnG2xldOxZIhMt43/Unp9SEkCaFjtgrFEknG3IKXIdpuoZS5XuJiF9++ovwA+9L6BirhaaIYStRtKcGQTEtK5WTVyG1JW/G843LgWGYFFsIkH4ki+X2BNJjei9QnyR5v4WGRm9KJBPhYIV9Zbu0RoMZ+9AXoUCou649NwiLVmzzHMv8SUzokj+a4z20qdsUm9EtgV2K7nw21jwcPUnqCo9Lf0syGznhIG6TwFPm2gF0LqqdzdHhNBl1wl/wOGVyVqvX7yDGiU7NwxkftFWlYyVRFaPgVglFmeSOv3qWJypa4mmZ6/EU+aafCMcWYTDn89PdjVsSeCGKSl4bO0xxnk16D6PVmZWfj9VZioYGX6TkosAtC5K5ic2HzgXDWP9i9t0FcWVVYgdxZeJ1TzNKwo6oS/IVE9eD8nH2FXhV1inKfirqBNX+PSHh/1mOsPzVar0mSg2yRPZTLCHx1sg/C6024AQtSowE7ps4FWi3eBEdJkttSO5dbQ3UzmRGZm/NdtpV8B1rX6nrJ3qe74x0ZfIuvv1l7V0v8CHWOQzBI7EYWsm9955cJJiWkOM4uPLITUhp/Q3baoJ8wjg23g7masa+OYVe6D6hdGajtW7u8vWUmq3OSGEDylVqkRhG66rE8zYuwhLKI6y0PcNllqzNxrSVRTYiMgXUTpBdwioN01m+nSQ4kShzyw9vqGYlJks7kPs4kqlYRNEf/HOwkB+bgGVhvQhXzB2e5/qvTr+nD8v3COe64ji594b5wyvRLO+Tom5M6gNc49D+jhrtfXlYEPuR0uCMK4R/rh5OldBPs4Xfu5VNR9JGzpsGWBHSCHjRoWD/2D8thk5naVSU1OX6cPkxM5TZNhFdeWq0yfImElODsffKFcdrT3ki11NNzqwFsUfQVmD19Si/5PjBmvxFQx+IZ+N3XoRxtYQiP95Ee9wTZttvqlLmZT0gWNFAaL731qeCVCo3IakAvDKMt0v1JnhRI4wgW5mv+ZPmxLdbGkFi89TNerlUq07qurMZgNE5FLJVahdIYprIZwPmsC3yzDOgmXegyfpnyaLnSF9SYMFHUVKRmZOLmNtGe4=
  template:
    metadata:
      creationTimestamp: null
      name: client-info-secret
      namespace: synology-csi
