apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: synology-iscsi-storage
provisioner: csi.san.synology.com
parameters:
  fsType: 'btrfs'
  dsm: '10.0.10.96' # has to be one dsm endpoint configured in the client-info.yml
  location: '/volume1' # specifies the volume you want to use to provision iscsi volume
  formatOptions: '--nodiscard'
reclaimPolicy: Delete
allowVolumeExpansion: true
