---

- name: Ensure ssh key configuration for ansible user
  ansible.posix.authorized_key:
    user: ansible
    state: present
    exclusive: true
    key: "{{ lookup('file', lookup('env', 'HOME') + '/' + ansible_public_key_path) }}"

- name: Ensure timezone is set
  community.general.timezone:
    name: "{{ timezone }}"
    hwclock: local


- name: Ensure hostname is set
  ansible.builtin.lineinfile:
    path: /etc/hostname
    regexp: "^"
    line: "{{ inventory_hostname }}"
  notify: Reboot the system


- name: Ensure hosts file is set
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1 {{ inventory_hostname }}"


- name: Generate locale
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locale_list }}"


- name: Flush handlers
  ansible.builtin.meta: flush_handlers
