---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: testsecret
spec:
  encryptedData:
    foo: AgCGtisqMMc1pbBKZVh/8i+EQSWxeMgxrRVqAN0lQpsJPIceMlWz4AomDqUqUwCbLcV0J2K7iPop7I+IqN464Gozx9eESAjFtNYy9NzVnyo+jTpYogsM2xeIiJiuShEQ1MecFqiIuJeabCwTfnKjsg1EmBlBW82mt5mxyoeKVFhM8KsBpkUCVz2rfe20MPuSyEG6NM2SMkHzLy+di60waVN/MZ4oGMhJegnKkfi9P1DPxXBpmampW16NwZ1toBojXmEY3FD0SOAG/L5KEd/6K9BNa2gNUk5ULM847NbsuK2jOE9lJR9qTludhJrluc9N2zZPFWNqbL+RQaOY4jgM0UCb7kAc3mtvZaMSNmT7ozm91AFpI1eSpG8UCnOgeTpPXGZf7EKNYi0I222FPPNON2Vd4SEsYLN58ldMirz2/5mG9jJHC9efoWk1/DHRn5YKRgTVD6XnpVxG89yH1vuiUcof9PuX8meNdgzl/zYNBPhTVYKrHihNyKG2VBdXxv2HyvEnJj7JgLKGeU2d5c5T5AbzuR7rzilA7oKJIcYu7pT1brdugxla9P4jAszGCtzihJCmWanojvNXr//7jNyu0h7gh2N4Pp1NVy1kX5aZFECvty7GezDsblpVF3q1TjepqO/KyRSA03DeV+O7XG1eExr6ia44aRSCd5ClYn9d4lzaebNP12XtrlJDFe6AXtDTXpCF2+TGv5L+Ww==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: testsecret
