---
apiVersion: v1
kind: Secret
metadata:
  name: services-secret
  namespace: media
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
type: Opaque
data:
  plex_claim: ""
  transmission_username: ""
  transmission_password: ""
