---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-secret
  namespace: media
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
type: Opaque
data:
  username: ""
  password: ""
